window.labelSet = {
    "id": "TTnCuK69AVDu5S5_JZgA4nG3",
    "author": "auth0|5b3a656445d8a648a1510a8b",
    "name": "English",
    "defaultId": 1,
    "defaultSet": true,
    "labels": {
        "quizNext": "NEXT",
        "tabGroup": "Tab",
        "codeGroup": "Code",
        "noteGroup": "Note",
        "quizScore": "Your score",
        "quizStart": "START QUIZ",
        "courseExit": "EXIT COURSE",
        "courseHome": "Home",
        "lessonName": "Lesson",
        "quizSubmit": "SUBMIT",
        "quoteGroup": "Quote",
        "salutation": "👋 Bye!",
        "buttonGroup": "Button",
        "courseStart": "START COURSE",
        "embedViewOn": "VIEW ON",
        "exitMessage": "You may now leave this page.",
        "quizCorrect": "Correct",
        "quizPassing": "PASSING",
        "quizResults": "Quiz Results",
        "courseResume": "RESUME COURSE",
        "quizLandmark": "Quiz",
        "quizQuestion": "Question",
        "courseDetails": "DETAILS",
        "embedReadMore": "Read more",
        "feedbackGroup": "Feedback",
        "quizIncorrect": "Incorrect",
        "quizTakeAgain": "TAKE AGAIN",
        "sortingReplay": "REPLAY",
        "accordionGroup": "Accordion",
        "embedLinkGroup": "Embedded web content",
        "lessonComplete": "COMPLETE",
        "statementGroup": "Statement",
        "storylineGroup": "Storyline",
        "attachmentGroup": "File Attachment",
        "embedPhotoGroup": "Embedded photo",
        "embedVideoGroup": "Embedded video",
        "playButtonLabel": "Play",
        "processComplete": "Complete",
        "processLandmark": "Process",
        "processNextStep": "NEXT STEP",
        "processStepName": "Step",
        "seekSliderLabel": "Seek",
        "sortingLandmark": "Sorting Activity",
        "audioPlayerGroup": "Audio player. You can use the space bar to toggle playback and arrow keys to scrub.",
        "buttonStackGroup": "Button stack",
        "embedPlayerGroup": "Embedded media player",
        "lessonRestricted": "Lessons must be completed in order",
        "pauseButtonLabel": "Pause",
        "textOnImageGroup": "Text on image",
        "timelineLandmark": "Timeline",
        "urlEmbedLandmark": "URL/Embed",
        "videoPlayerGroup": "Video player. You can use the space bar to toggle playback and arrow keys to scrub.",
        "blocksClickToFlip": "Click to flip",
        "blocksPreposition": "of",
        "bulletedListGroup": "Bulleted list",
        "checkboxListGroup": "Checkbox list",
        "imageAndTextGroup": "Image and text",
        "imageGalleryGroup": "Image gallery",
        "lessonPreposition": "of",
        "numberedListGroup": "Numbered list",
        "processLessonName": "Lesson",
        "processStartAgain": "START AGAIN",
        "courseSkipToLesson": "SKIP TO LESSON",
        "flashcardBackLabel": "Flashcard back",
        "flashcardGridGroup": "Flashcard grid",
        "nextFlashCardLabel": "Next flashcard",
        "flashcardFrontLabel": "Flashcard front",
        "flashcardStackGroup": "Flashcard stack",
        "knowledgeCheckGroup": "Knowledge check",
        "sortingCardsCorrect": "Cards Correct",
        "hamburgerButtonLabel": "Course Overview Sidebar",
        "lessonHeaderLandmark": "Lesson Header",
        "numberedDividerGroup": "Numbered divider",
        "lessonContentLandmark": "Lesson Content",
        "lessonSidebarLandmark": "Lesson Sidebar",
        "quizAnswerPlaceholder": "Type your answer here",
        "labeledGraphicLandmark": "Labeled Graphic",
        "previousFlashCardLabel": "Previous flashcard",
        "processStepPreposition": "of",
        "overviewPageTitleSuffix": "Overview",
        "quizAcceptableResponses": "Acceptable responses",
        "quizRequirePassingScore": "Must pass quiz before continuing",
        "timelineCardGroupPrefix": "Timeline Card",
        "labeledGraphicBubbleLabel": "Labeled graphic bubble",
        "labeledGraphicMarkerLabel": "Labeled graphic marker",
        "labeledGraphicNextMarkerLabel": "Next marker",
        "labeledGraphicPreviousMarkerLabel": "Previous marker",
        "quizContinue": "Continue",
        "processStart": "START",
        "processSwipe": "Swipe to continue",
        "search": "search",
        "result": "result",
        "results": "results",
        "noResults": "No results for",
        "scenarioTryAgain": "TRY AGAIN",
        "scenarioContinue": "CONTINUE",
        "scenarioComplete": "Scenario Complete!",
        "scenarioStartOver": "START OVER"
    },
    "deleted": false,
    "createdAt": "2018-07-02T17:55:17.867Z",
    "updatedAt": "2018-07-02T17:55:17.867Z",
    "iso639Code": "en",
    "transferredAt": null
};